sudo: false
language: erlang
otp_release:
  - "19.3"
  - "20.0"
cache:
  directories:
  - $HOME/otp/19.3
  - $HOME/otp/20.0
  - $HOME/.cache/rebar3
  - _plt
install: "true"
script: "make travis"
branches:
  only:
    - master
    - develop
notifications:
  email:
    - pj@ezgr.net

